# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-25 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('sartTime', models.CharField(default='00:00', max_length=400)),
                ('endTime', models.CharField(default='00:00', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField(auto_now=True)),
                ('seen', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='UserNotification',
            new_name='AdminNotifications',
        ),
        migrations.RenameModel(
            old_name='Request',
            new_name='Requests',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='tickets',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tickets'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='sans',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Sans'),
            preserve_default=False,
        ),
    ]
