# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-25 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20180825_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sans',
            old_name='sartTime',
            new_name='startTime',
        ),
        migrations.RemoveField(
            model_name='usernotifications',
            name='time',
        ),
        migrations.AddField(
            model_name='requests',
            name='priority',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
